/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.2/userguide/building_java_projects.html
 */

plugins {
    id("io.spring.dependency-management") version "1.0.11.RELEASE"
}

repositories {
    mavenCentral()
}
subprojects {

    version = "1.0.0_SNAPSHOT"
    group = "com.pocket-creed"

    plugins.apply("io.spring.dependency-management")
    plugins.apply("java")
    plugins.apply("java-library")

    repositories {
        mavenCentral()
    }

    dependencyManagement{
        imports{
            mavenBom("org.springframework.boot:spring-boot-dependencies:2.6.0")
        }
    }
}


