package com.pocket.creed.keywords.faction.imperium.adeptus_custodes;

import com.pocket.creed.keywords.faction.Faction;
import lombok.Getter;

public enum AdeptusCustodesKeyWord implements Faction {
    ADEPTUS_CUSTODES("ADEPTUS CUSTODES"),
    CAPTAIN_GENERAL_TRAJANN_VALORIS("CAPTAIN-GENERAL TRAJANN VALORIS"),
    VALERIAN("VALERIAN"),
    ALEYA("ALEYA"),
    SHIELD_CAPTAIN("SHIELD CAPTAIN"),
    CUSTODIAN_GUARD("CUSTODIAN GUARD"),
    SAGITTARUM_CUSTODIANS("SAGITTARUM CUSTODIANS"),
    CUSTODIAN_WARDENS("CUSTODIAN WARDENS"),
    ALLARUS_CUSTODIANS("ALLARUS CUSTODIANS"),
    AQUILON_CUSTODIANS("AQUILON CUSTODIANS"),
    CORONUS_GRAV_CARRIER("CORONUS GRAV CARRIER"),
    VENERABLE_CONTEMPTOR_DREADNOUGHT("VENERABLE CONTEMPTOR DREADNOUGHT"),
    VEXILUS_PRAETOR("VEXILUS PRAETOR"),
    CONTEMPTOR_ACHILLUS_DREADNOUGHT("CONTEMPTOR ACHILLUS DREADNOUGHT"),
    CONTEMPTOR_GALATUS_DREADNOUGHT("CONTEMPTOR GALATUS DREADNOUGHT"),
    VERTUS_PRAETORS("VERTUS PRAETORS"),
    VENATARI_CUSTODIANS("VENATARI CUSTODIANS"),
    AGAMATUS_CUSTODIANS("AGAMATUS CUSTODIANS"),
    PALLAS_GRAV_ATTACK("PALLAS GRAV ATTACK"),
    ARES_GUNSHIP("ARES GUNSHIP"),
    ORION_ASSAULT_DROPSHIP("ORION ASSAULT DROPSHIP"),
    VENERABLE_LAND_RAIDER("VENERABLE LAND RAIDER"),
    CALADIUS_GRAV_TANK("CALADIUS GRAV TANK"),
    TELEMON_HEAVY_DREADNOUGHT("TELEMON HEAVY DREADNOUGHT");

    @Getter
    private final String value;

    AdeptusCustodesKeyWord(String value) {
        this.value = value;
    }
}
